### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by robertherber** [kingstinct/react-native-motion-activity-tracker#9]
A few suggestions:
- Small detail but nice to make endDate optional for getHistoricalData. Default to `new Date()` (easy to do on the TypeScript side)
- Rename `getHistoricalDataIos` to `getHistoricalData`. Provide a default implementation for other platforms that returns an empty array and also logs a warning that the function is not supported. Would be nice to indicate with JSDoc comments that the function is iOS only as well, this will make it easy to see at a glance in VSCode/Cursor.
- Provide a fallback implementation for unsupported platforms. Currently importing the module results in errors on web for example where the native part doesn't exist. One good way of doing this would be to rename `MotionActivityTracker.ts` to `MotionActivityTracker.native.ts`, and create a new MotionActivityTracker.ts with just fallback functions.

I think the [UnavailableFn](https://github.com/kingstinct/react-native-healthkit/blob/5ee5c1cbd880a850637cab341e72a270bd4415f1/src/index.native.tsx#L17) in react-native-healthkit is a pretty nice way to implement fallback functions on unsupported platforms.

**Comment by RevanToma** [comment]
@robertherber thank you robert for the issue, i will work on it!

**Comment by RevanToma** [comment]
@robertherber 
I'm happy to let you know that your suggestion has been implemented in version 1.0.0 of the library. Here's what has been updated:

Renamed getHistoricalDataIOS to getHistoricalData.
Made endDate optional for getHistoricalData (defaults to new Date()).
Added fallback implementations for unsupported platforms.
